### ISSUE TITLE
Probably Chests causing crashes upon starting the game.

### ISSUE THREAD

**Issue by 1North** [ReillyGregorio/ProbablyChests#1] opened 2022-04-14 21:19 UTC
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/14/22, 11:12 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'probablychests'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/SyncedGuiDescription
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.cloudwarp.probablychests.registry.PCBlockEntities.<clinit>(PCBlockEntities.java:23)
	at org.cloudwarp.probablychests.ProbablyChests.onInitialize(ProbablyChests.java:36)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.cotton.gui.SyncedGuiDescription
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1586 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.1202 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2203.5 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1586 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.1586 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1586 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.746 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.1503 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll
		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jna3234083851495563553.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1586 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		win32u.dll:Win32u:10.0.19041.1586 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1586 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2126061568 bytes (2027 MiB) / 3279945728 bytes (3128 MiB) up to 4831838208 bytes (4608 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6600 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: DriverVersion=30.0.13037.1003
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37579.96
	Virtual memory used (MB): 15810.98
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4608m -Xms256m
	Fabric Mods: 
		advancednetherite: Advanced Netherite 1.4.1-1.18.2
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.1.44
		artifacts: Artifacts 7.0.1+fabric
		autoclicker-fabric: Auto Clicker 1.18-1.3.0-build.16
		autofish: Autofish 0.9.4
		betterbiomeblend: Better Biome Blend 1.18.2-1.3.4-fabric
		bettermounthud: Better Mount HUD 1.1.4
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bookshelf: Bookshelf 13.0.12
		borderlessmining: Borderless Mining 1.1.1+1.18
		caffeineconfig: CaffeineConfig 1.1.0
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-level: Cardinal Components API (world saves) 4.0.1
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chipped: Chipped 1.2
		cloth-api: Cloth API 3.2.64
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.2.64
		cloth-common-events-v1: Cloth Common Events v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
		cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
		cloth-utils-v1: Cloth Utils v1 3.2.64
		clumps: Clumps 8.0.0+7
		collective-fabric: Collective (Fabric) 4.26
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_llamalad7_mixinextras: MixinExtras 0.0.7
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		consistency_plus: Consistency Plus 0.5.0-RC3+1.18.2
		continuity: Continuity 1.1.0+1.18.2
		couplings: Couplings 1.8.0+1.18.2
		croptopia: Croptopia 1.8.3
		denseores: Dense Ores: Refabricated 1.2.2+1.18.2
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		duckling: Duckling 1.0.3
		dynamicfps: Dynamic FPS 2.1.0
		eatinganimationid: Eating Animation 1.6
		ecologics: Ecologics 1.5.2
		effective: Effective 1.2.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		equipmentcompare: Equipment Compare 1.2.12
		expandability: ExpandAbility 6.0.0
		fabric: Fabric API 0.50.0+1.18.2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		ferritecore: FerriteCore 4.2.0
		fiber: fiber 0.23.0-2
		friendsandfoes: Friends&Foes 1.3.4
		geckolib3: Geckolib 3.0.36
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.11
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.2+mc1.18.2
		indypets: Independent Pets 0.8.1
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.6-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0
		kyrptconfig: Kyrpt Config 1.4.2-1.18
		lambdabettergrass: LambdaBetterGrass 1.2.3+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		libzoomer: LibZoomer 0.4.2+1.18.2
		lightoverlay: Light Overlay 6.1.0
		litematica: Litematica 0.11.2
		lovely_snails: Lovely Snails 1.0.4+1.18
		malilib: MaLiLib 0.12.1
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		mobscarecrow: Mob Scarecrow 1.2.2
		modmenu: Mod Menu 3.1.1
		mousetweaks: Mouse Tweaks 2.22
		okzoomer: Ok Zoomer 5.0.0-beta.6+1.18.2
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.3-1.18.1
		org_javassist_javassist: javassist 3.26.0-GA
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_reflections_reflections: reflections 0.9.12
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		patchouli: Patchouli 1.18.2-67-FABRIC
		presencefootsteps: Presence Footsteps 1.5.0
		pride: Pride Lib 1.1.0+1.17
		probablychests: Probably Chests 0.3.0
		quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
		quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
		quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
		quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 3.0.0+1.18.2-SNAPSHOT
		quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.2+1.18.2-SNAPSHOT
		reborncore: Reborn Core 5.2.0-beta.2
		rhino: Rhino 1801.1.9-build.135
		rightclickharvest: Right Click Harvest 1.5.1
		saplanting: Saplanting fabric-1.18.2-1.1-rc-3
		satin: Satin 1.7.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.7+1.18.2
		sit: Sit 1.18.2-18
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.3
		spruceui: SpruceUI 3.3.3+1.18
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 3.0.1+1.18.bc850d5.fabric
		team_reborn_energy: Energy 2.2.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.0
		twigs: Twigs 1.1.3-patch1+1.18.2
		valhelsia_core: Valhelsia Core 1.18.2-fabric-0.3.0
		villagernames: Villager Names 4.0.3
		wildlife: Wildlife 1.18.2-1.0
		worldedit: WorldEdit 7.2.10+1742f98
		wthit: wthit 4.8.1
		xaerominimap: Xaero's Minimap 22.5.0
		xaeroworldmap: Xaero's World Map 1.20.6
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by ArcanePigeon** [comment] 2022-04-14 22:07
Could you send me your modpack so I can try and find the issue. It seems like a compatibility issue with one of the mods you have. The error message is weird as my mod has the mod has the library that it is failing to find compiled in. Could you also join the discord so I can get more information?

**Comment by 1North** [comment] 2022-04-14 22:11
I've found that disabling Ok Zoomer allows me to launch minecraft properly.

edit: it's a custom modpack, aka made it myself.

**Comment by ArcanePigeon** [comment] 2022-06-17 07:34
Labeling this a wont fix as the issue is with fabric and PC will be moving to quilt in the future which will solve the issue.

**Closed as completed by ArcanePigeon** 2022-06-17 07:34 UTC
Labels: wontfix
